# Generated by Django 3.1.3 on 2022-04-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(db_column='description', max_length=1000)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(db_column='description', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de risco',
                'verbose_name_plural': 'Tipos de risco',
                'db_table': 'risktype',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('risk', models.TextField(db_column='risk', null=True)),
                ('how_to_assess', models.TextField(db_column='how_to_assess', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.category')),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.risktype')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
            },
        ),
    ]
