# Generated by Django 3.1.3 on 2022-04-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20220409_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='how_to_correct',
            field=models.TextField(db_column='how_to_correct', null=True),
        ),
    ]
