version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=Mcpjst22p
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres/data:/var/lib/postgresql/data/pgdata
#  complyant:
#    ports:
#      - 8001:8000
#    image: andretapxure/complyant
#    depends_on:
#      - postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres
  metabase:
    image: metabase/metabase:latest
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: ABC@123@
      MB_DB_HOST: postgres
    depends_on:
      - postgres