# Generated by Django 3.1.3 on 2022-04-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('description', models.TextField(db_column='description', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Compliance Level',
                'verbose_name_plural': 'Compliance Levels',
                'db_table': 'compliancelevel',
            },
        ),
        migrations.CreateModel(
            name='AssessmentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measures', models.TextField(blank=True, db_column='measures', max_length=1000, null=True)),
                ('reasonfornotapplicable', models.TextField(blank=True, db_column='reasonfornotapplicable', max_length=1000, null=True)),
                ('assessment', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
                ('compliance_level', models.ForeignKey(db_column='compliance_level', on_delete=django.db.models.deletion.CASCADE, to='assessmentitems.compliancelevel')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
            options={
                'verbose_name': 'Assessment Items',
                'verbose_name_plural': 'Assessment Items',
                'db_table': 'assessmentitems',
            },
        ),
    ]
