# Generated by Django 3.1.3 on 2022-04-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentitems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentitems',
            name='compliance_level',
            field=models.ForeignKey(db_column='compliance_level_id', on_delete=django.db.models.deletion.CASCADE, to='assessmentitems.compliancelevel'),
        ),
    ]
